### ISSUE TITLE
Migrate to claroline/Distribution

### ISSUE THREAD

**Issue by stefk** [claroline/DevBundle#13]
We need it as a dev dependency of claroline/Distribution (e.g. for travis) but it's itself dependent on that repo. This isn't only weird for maintenance, it seems to break composer when using branch aliases (https://travis-ci.org/stefk/Distribution/builds/120916837).

One solution is to migrate the contents of this bundle to the core and exclude them from prod using git attributes (see claroline/Distribution#5).

**Comment by stefk** [comment]
Closed by claroline/Distribution#132.

**Comment by ngodfraind** [comment]
Tu veux que je vire le commit et le refasse avec l'historique ?

2016-04-12 10:50 GMT+02:00 Stéphane Klein <notifications@github.com>:

> Closed #13 <https://github.com/claroline/DevBundle/issues/13>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/DevBundle/issues/13#event-623779439>
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by stefk** [comment]
Pas nécessaire (le master est protégé en plus), faut juste faire attention à l'avenir.
